name: Reset Skip Signal # resets the skip signal

on:
  schedule:
    - cron: '0 11 * * *' # Run at midnight UTC
  workflow_dispatch:

jobs:
  reset_signal:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Skip Signal
        run: |
          # Close any open skip issues
          gh issue list -l skip --json number --state open --limit 100 | jq -r '.[] | .number' | xargs -I {} gh issue close {}
