name: Keep my Duolingo streak -- Cron + Manual Trigger # random times
# This workflow runs at a random time between 6:00 PM and 11:40 PM (UTC/GMT).
# If, for any reason, I haven't used the Duolingo app by 6:00 PM, the workflow will ensure
# the streak continues by setting a random time between 6:00 PM and 11:00 PM (UTC/GMT).
on:
  schedule:
    - cron: '2 18 * * *'  # Runs at 7:02PM UTC+1
  workflow_dispatch:      # Triggered Manually from the Actions Page
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be completed'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Calculate random delay
        id: random_delay
        run: |
          # Calculate a random number of seconds between 0 and 20,400 (5 hours 40 minutes)
          RANDOM_DELAY=$(( RANDOM % 20400 ))
          echo "Random delay in seconds: $RANDOM_DELAY" > random_delay.txt
          echo "delay=$RANDOM_DELAY" >> $GITHUB_ENV

      - name: Sleep for random delay
        run: |
          DELAY="${{ env.delay }}"
          echo "DELAY value: $DELAY"
          echo "Sleeping for $((DELAY / 60)) minutes. ($DELAY seconds)"
          sleep "$DELAY"

      - name: Run the Duolingo script
        run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          #LESSONS: 1
          LESSONS: ${{ inputs.lessons }}
