name: Keep my Duolingo streak # random times

on:
  schedule:
    - cron: '18 1 * * *' # Run at 2:18 AM UTC+1

jobs:
  study:
    runs-on: ubuntu-latest # GitHub Actions doesn't support Windows 11; ubuntu-latest is the closest option
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Calculate random delay
        id: random_delay
        run: |
          # Calculate a random number of seconds between 0 and 20,400 (5 hours 40 minutes)
          RANDOM_DELAY=$(( RANDOM % 20400 ))
          echo "Random delay in seconds: $RANDOM_DELAY"
          echo "::set-output name=delay::$RANDOM_DELAY"

      - name: Sleep for random delay
        run: |
          DELAY=${{ steps.random_delay.outputs.delay }}
          echo "Sleeping for $DELAY seconds"
          sleep $DELAY

      - name: Run the Duolingo script
        run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 1
